Repository traceloop/openllmetry, pull requests merged in 2024-09, with the labels that each got.

#1985 fix(langchain): support v0.3.0
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
  packages/opentelemetry-instrumentation-langchain/poetry.lock
  packages/opentelemetry-instrumentation-langchain/pyproject.toml
  packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py
Labels: bug, python, size:S

#2000 feat(sdk+openai): support base64 images upload
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/__init__.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/config.py
  packages/opentelemetry-instrumentation-openai/tests/traces/conftest.py
  packages/opentelemetry-instrumentation-openai/tests/traces/test_vision.py
  packages/sample-app/data/vision/elephant.jpeg
  packages/sample-app/sample_app/openai_vision_base64_example.py
  packages/traceloop-sdk/traceloop/sdk/__init__.py
  packages/traceloop-sdk/traceloop/sdk/images/image_uploader.py
  packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Labels: python, testing, size:L, lgtm

#2015 fix(sdk): wrong package check for Vertex AI
  packages/sample-app/sample_app/vertexai_streaming.py
  packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Labels: python, size:M, lgtm

#2030 fix(anthropic): token counting exception when prompt contains images
  packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py
  packages/opentelemetry-instrumentation-anthropic/tests/test_completion.py
Labels: python, size:M, lgtm

#2051 fix: support async image upload flows
  packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py
  packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/config.py
  packages/opentelemetry-instrumentation-anthropic/tests/cassettes/test_completion/test_anthropic_async_multi_modal.yaml
  packages/opentelemetry-instrumentation-anthropic/tests/conftest.py
  packages/opentelemetry-instrumentation-anthropic/tests/test_completion.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/__init__.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py
  packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_vision/test_vision_base64.yaml
  packages/opentelemetry-instrumentation-openai/tests/traces/conftest.py
  packages/opentelemetry-instrumentation-openai/tests/traces/test_vision.py
  packages/sample-app/poetry.lock
  packages/sample-app/sample_app/anthropic_vision_base64_example.py
  packages/traceloop-sdk/traceloop/sdk/images/image_uploader.py
  packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Labels: dependencies, python, size:L, lgtm
