Repository traceloop/openllmetry, pull requests merged in 2024-10, with the labels that each got.

#2064 fix(sdk): custom image uploader
  packages/traceloop-sdk/traceloop/sdk/__init__.py
Labels: python, size:XS, lgtm

#2065 fix(langchain): serialize inputs and outputs with pydantic
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
  packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py
  packages/opentelemetry-instrumentation-langchain/tests/test_llms.py
Labels: python, testing, size:L

#2028 feat(SageMaker): Add SageMaker instrumentation
  README.md
  packages/opentelemetry-instrumentation-sagemaker/.flake8
  packages/opentelemetry-instrumentation-sagemaker/.python-version
  packages/opentelemetry-instrumentation-sagemaker/README.md
  packages/opentelemetry-instrumentation-sagemaker/opentelemetry/instrumentation/sagemaker/__init__.py
  packages/opentelemetry-instrumentation-sagemaker/opentelemetry/instrumentation/sagemaker/config.py
  packages/opentelemetry-instrumentation-sagemaker/opentelemetry/instrumentation/sagemaker/reusable_streaming_body.py
  packages/opentelemetry-instrumentation-sagemaker/opentelemetry/instrumentation/sagemaker/streaming_wrapper.py
  packages/opentelemetry-instrumentation-sagemaker/opentelemetry/instrumentation/sagemaker/utils.py
  packages/opentelemetry-instrumentation-sagemaker/opentelemetry/instrumentation/sagemaker/version.py
  packages/opentelemetry-instrumentation-sagemaker/poetry.lock
  packages/opentelemetry-instrumentation-sagemaker/poetry.toml
  packages/opentelemetry-instrumentation-sagemaker/project.json
  packages/opentelemetry-instrumentation-sagemaker/pyproject.toml
  packages/opentelemetry-instrumentation-sagemaker/tests/__init__.py
  packages/opentelemetry-instrumentation-sagemaker/tests/cassettes/test_invocation/test_sagemaker_completion_string_content.yaml
  packages/opentelemetry-instrumentation-sagemaker/tests/conftest.py
  packages/opentelemetry-instrumentation-sagemaker/tests/test_invocation.py
  packages/traceloop-sdk/poetry.lock
  packages/traceloop-sdk/pyproject.toml
  packages/traceloop-sdk/traceloop/sdk/instruments.py
  packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Labels: new instrumentation, python, testing, size:XL, lgtm

#1957 feat(bedrock): support metrics for bedrock
  packages/opentelemetry-instrumentation-bedrock/opentelemetry/instrumentation/bedrock/__init__.py
  packages/opentelemetry-instrumentation-bedrock/tests/conftest.py
  packages/opentelemetry-instrumentation-bedrock/tests/metrics/__init__.py
  packages/opentelemetry-instrumentation-bedrock/tests/metrics/cassettes/test_bedrock_metrics/test_invoke_model_metrics.yaml
  packages/opentelemetry-instrumentation-bedrock/tests/metrics/test_bedrock_metrics.py
  packages/opentelemetry-instrumentation-bedrock/tests/traces/__init__.py
  packages/opentelemetry-instrumentation-bedrock/tests/traces/cassettes/test_ai21/test_ai21_j2_completion_string_content.yaml
  packages/opentelemetry-instrumentation-bedrock/tests/traces/cassettes/test_anthropic/test_anthropic_2_completion.yaml
  packages/opentelemetry-instrumentation-bedrock/tests/traces/cassettes/test_anthropic/test_anthropic_3_completion_complex_content.yaml
  packages/opentelemetry-instrumentation-bedrock/tests/traces/cassettes/test_anthropic/test_anthropic_3_completion_streaming.yaml
  packages/opentelemetry-instrumentation-bedrock/tests/traces/cassettes/test_anthropic/test_anthropic_3_completion_string_content.yaml
  packages/opentelemetry-instrumentation-bedrock/tests/traces/cassettes/test_meta/test_meta_llama2_completion_string_content.yaml
  packages/opentelemetry-instrumentation-bedrock/tests/traces/cassettes/test_meta/test_meta_llama3_completion.yaml
  packages/opentelemetry-instrumentation-bedrock/tests/traces/cassettes/test_titan/test_titan_completion.yaml
  packages/opentelemetry-instrumentation-bedrock/tests/traces/test_ai21.py
  packages/opentelemetry-instrumentation-bedrock/tests/traces/test_anthropic.py
  packages/opentelemetry-instrumentation-bedrock/tests/traces/test_meta.py
  packages/opentelemetry-instrumentation-bedrock/tests/traces/test_titan.py
Labels: python, testing, size:L, lgtm

#2074 fix(langchain): token usage reporting
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
  packages/opentelemetry-instrumentation-langchain/poetry.lock
  packages/opentelemetry-instrumentation-langchain/tests/test_chains.py
  packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py
  packages/opentelemetry-instrumentation-langchain/tests/test_llms.py
Labels: python, testing, size:L, lgtm

#2086 fix(anthropic): Replace count_tokens with usage for newer models
  packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py
  packages/opentelemetry-instrumentation-anthropic/tests/test_completion.py
Labels: python, testing, size:L, lgtm

#2094 fix(traceloop-sdk): add aiohttp as dependency
  packages/traceloop-sdk/poetry.lock
  packages/traceloop-sdk/pyproject.toml
Labels: dependencies, size:XS

#2059 feat(ollama): tool calling
  packages/opentelemetry-instrumentation-ollama/opentelemetry/instrumentation/ollama/__init__.py
  packages/opentelemetry-instrumentation-ollama/poetry.lock
  packages/opentelemetry-instrumentation-ollama/pyproject.toml
  packages/opentelemetry-instrumentation-ollama/tests/cassettes/test_chat/test_ollama_chat_tool_calls.yaml
  packages/opentelemetry-instrumentation-ollama/tests/test_chat.py
Labels: python, testing, size:L, lgtm

#2102 docs(readme): contributors list; links to LLM providers
  CONTRIBUTING.md
  README.md
Labels: documentation, size:M, lgtm

#2112 feat(sdk): add OpenTelemetry logging support
  packages/traceloop-sdk/poetry.lock
  packages/traceloop-sdk/pyproject.toml
  packages/traceloop-sdk/traceloop/sdk/__init__.py
  packages/traceloop-sdk/traceloop/sdk/config/__init__.py
  packages/traceloop-sdk/traceloop/sdk/logging/__init__.py
  packages/traceloop-sdk/traceloop/sdk/logging/logging.py
Labels: python, size:L, lgtm

#2141 fix(llama-index): add attribute to span for llm request type in dispatcher wrapper
  packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/dispatcher_wrapper.py
  packages/opentelemetry-instrumentation-llamaindex/tests/test_agents.py
Labels: python, testing, size:XS, lgtm

#2111 fix(openai): add structured output instrumentation
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/v1/__init__.py
  packages/opentelemetry-instrumentation-openai/poetry.lock
  packages/opentelemetry-instrumentation-openai/pyproject.toml
  packages/opentelemetry-instrumentation-openai/tests/metrics/cassettes/test_openai_metrics/test_chat_parsed_completion_metrics.yaml
  packages/opentelemetry-instrumentation-openai/tests/metrics/test_openai_metrics.py
  packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_structured/test_async_parsed_completion.yaml
  packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_structured/test_async_parsed_refused_completion.yaml
  packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_structured/test_parsed_completion.yaml
  packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_structured/test_parsed_refused_completion.yaml
  packages/opentelemetry-instrumentation-openai/tests/traces/test_structured.py
Labels: python, testing, size:XL, lgtm

#2150 fix(anthropic): add instrumentation for Anthropic tool calling (alternative to #1372)
  packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py
  packages/opentelemetry-instrumentation-anthropic/poetry.lock
  packages/opentelemetry-instrumentation-anthropic/pyproject.toml
  packages/opentelemetry-instrumentation-anthropic/tests/cassettes/test_completion/test_anthropic_tools.yaml
  packages/opentelemetry-instrumentation-anthropic/tests/test_completion.py
Labels: python, testing, size:L, lgtm

#2152 fix(langchain): Add trace context to client requests
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/__init__.py
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_llms/test_trace_propagation[ChatOpenAI].yaml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_llms/test_trace_propagation[OpenAI].yaml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_llms/test_trace_propagation[VLLMOpenAI].yaml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_llms/test_trace_propagation_async[ChatOpenAI].yaml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_llms/test_trace_propagation_async[OpenAI].yaml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_llms/test_trace_propagation_async[VLLMOpenAI].yaml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_llms/test_trace_propagation_stream[ChatOpenAI].yaml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_llms/test_trace_propagation_stream[OpenAI].yaml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_llms/test_trace_propagation_stream[VLLMOpenAI].yaml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_llms/test_trace_propagation_stream_async[ChatOpenAI].yaml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_llms/test_trace_propagation_stream_async[OpenAI].yaml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_llms/test_trace_propagation_stream_async[VLLMOpenAI].yaml
  packages/opentelemetry-instrumentation-langchain/tests/test_llms.py
Labels: python, testing, size:XXL, lgtm

#2153 ci: fix flakiness in langchain tests
  packages/opentelemetry-instrumentation-langchain/tests/conftest.py
Labels: testing, size:XS

#2154 fix(langchain): metrics support
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/__init__.py
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_agents/test_agents.yaml
  packages/opentelemetry-instrumentation-langchain/tests/conftest.py
  packages/opentelemetry-instrumentation-langchain/tests/metrics/cassettes/test_langchain_metrics/test_llm_chain_metrics.yaml
  packages/opentelemetry-instrumentation-langchain/tests/metrics/cassettes/test_langchain_metrics/test_llm_chain_streaming_metrics.yaml
  packages/opentelemetry-instrumentation-langchain/tests/metrics/test_langchain_metrics.py
  packages/opentelemetry-instrumentation-langchain/tests/test_agents.py
Labels: python, testing, size:L, lgtm

#2164 fix(sdk): add header for logging exporter
  packages/traceloop-sdk/traceloop/sdk/__init__.py
  packages/traceloop-sdk/traceloop/sdk/logging/logging.py
Labels: bug, python, size:S, lgtm

#2167 fix(langchain): various bugs and edge cases in metric exporting
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
Labels: bug, python, size:S, lgtm

#2194 fix(sdk): capture posthog events as anonymous; roll ingestion key
  packages/traceloop-sdk/poetry.lock
  packages/traceloop-sdk/traceloop/sdk/telemetry.py
Labels: python, size:XS, lgtm

#2214 fix(langchain): structured output response parsing
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/utils.py
  packages/opentelemetry-instrumentation-langchain/poetry.lock
  packages/opentelemetry-instrumentation-langchain/pyproject.toml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_structured_output/test_structured_output.yaml
  packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py
  packages/opentelemetry-instrumentation-langchain/tests/test_llms.py
  packages/opentelemetry-instrumentation-langchain/tests/test_structured_output.py
  packages/sample-app/poetry.lock
  packages/sample-app/pyproject.toml
  packages/sample-app/sample_app/langchain_lcel.py
Labels: bug, python, size:L, lgtm

#2226 fix(openai+anthropic): async call crashing the app when already in a running asyncio loop
  packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py
  packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/utils.py
  packages/opentelemetry-instrumentation-anthropic/tests/cassettes/test_completion/test_with_asyncio_run.yaml
  packages/opentelemetry-instrumentation-anthropic/tests/test_completion.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/utils.py
  packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_chat/test_with_asyncio_run.yaml
  packages/opentelemetry-instrumentation-openai/tests/traces/test_chat.py
Labels: bug, python, size:L, lgtm

#2222 chore(docs): fixed broken link in readme.md
  README.md
Labels: documentation, size:XS, lgtm

#1958 fix(sdk): support a "block-list" of things to not instrument
  packages/traceloop-sdk/tests/conftest.py
  packages/traceloop-sdk/traceloop/sdk/__init__.py
  packages/traceloop-sdk/traceloop/sdk/instruments.py
  packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Labels: new instrumentation, python, size:L, lgtm

#2235 fix(sdk): missing sagemaker initialization
  packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Labels: bug, size:L
