Repository traceloop/openllmetry, pull requests merged in 2024-12, with the labels that each got.

#2383 fix(sdk): Update JSONEncoder to allow class instance methods to be serializable
  packages/traceloop-sdk/tests/test_class_tasks.py
  packages/traceloop-sdk/traceloop/sdk/utils/json_encoder.py
Labels: python, size:M, lgtm

#2382 fix: update google generative AI import
  packages/opentelemetry-instrumentation-google-generativeai/README.md
Labels: documentation, size:XS, lgtm

#2384 feat(docs): Update README.md to add link to recently-added GCP integration document.
  README.md
Labels: documentation, size:XS, lgtm

#2386 fix: bump otel >0.50b0
  packages/opentelemetry-instrumentation-alephalpha/poetry.lock
  packages/opentelemetry-instrumentation-alephalpha/pyproject.toml
  packages/opentelemetry-instrumentation-anthropic/poetry.lock
  packages/opentelemetry-instrumentation-anthropic/pyproject.toml
  packages/opentelemetry-instrumentation-bedrock/poetry.lock
  packages/opentelemetry-instrumentation-bedrock/pyproject.toml
  packages/opentelemetry-instrumentation-chromadb/poetry.lock
  packages/opentelemetry-instrumentation-chromadb/pyproject.toml
  packages/opentelemetry-instrumentation-cohere/poetry.lock
  packages/opentelemetry-instrumentation-cohere/pyproject.toml
  packages/opentelemetry-instrumentation-google-generativeai/poetry.lock
  packages/opentelemetry-instrumentation-google-generativeai/pyproject.toml
  packages/opentelemetry-instrumentation-groq/poetry.lock
  packages/opentelemetry-instrumentation-groq/pyproject.toml
  packages/opentelemetry-instrumentation-haystack/poetry.lock
  packages/opentelemetry-instrumentation-haystack/pyproject.toml
  packages/opentelemetry-instrumentation-lancedb/poetry.lock
  packages/opentelemetry-instrumentation-lancedb/pyproject.toml
  packages/opentelemetry-instrumentation-langchain/poetry.lock
  packages/opentelemetry-instrumentation-langchain/pyproject.toml
  packages/opentelemetry-instrumentation-llamaindex/poetry.lock
  packages/opentelemetry-instrumentation-llamaindex/pyproject.toml
  packages/opentelemetry-instrumentation-marqo/poetry.lock
  packages/opentelemetry-instrumentation-marqo/pyproject.toml
  packages/opentelemetry-instrumentation-milvus/poetry.lock
  packages/opentelemetry-instrumentation-milvus/pyproject.toml
  packages/opentelemetry-instrumentation-mistralai/poetry.lock
  packages/opentelemetry-instrumentation-mistralai/pyproject.toml
  packages/opentelemetry-instrumentation-ollama/poetry.lock
  packages/opentelemetry-instrumentation-ollama/pyproject.toml
  packages/opentelemetry-instrumentation-openai/poetry.lock
  packages/opentelemetry-instrumentation-openai/pyproject.toml
  packages/opentelemetry-instrumentation-pinecone/poetry.lock
  packages/opentelemetry-instrumentation-pinecone/pyproject.toml
  packages/opentelemetry-instrumentation-qdrant/poetry.lock
  packages/opentelemetry-instrumentation-qdrant/pyproject.toml
  packages/opentelemetry-instrumentation-replicate/poetry.lock
  packages/opentelemetry-instrumentation-replicate/pyproject.toml
  packages/opentelemetry-instrumentation-sagemaker/poetry.lock
  packages/opentelemetry-instrumentation-sagemaker/pyproject.toml
  packages/opentelemetry-instrumentation-together/poetry.lock
  packages/opentelemetry-instrumentation-together/pyproject.toml
  packages/opentelemetry-instrumentation-transformers/poetry.lock
  packages/opentelemetry-instrumentation-transformers/pyproject.toml
  packages/opentelemetry-instrumentation-vertexai/poetry.lock
  packages/opentelemetry-instrumentation-vertexai/pyproject.toml
  packages/opentelemetry-instrumentation-watsonx/poetry.lock
  packages/opentelemetry-instrumentation-watsonx/pyproject.toml
  packages/opentelemetry-instrumentation-weaviate/poetry.lock
  packages/opentelemetry-instrumentation-weaviate/pyproject.toml
  packages/sample-app/poetry.lock
  packages/traceloop-sdk/poetry.lock
  packages/traceloop-sdk/pyproject.toml
Labels: dependencies, size:M

#2416 fix(langchain): azure openai missing request model
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
Labels: bug, size:S, lgtm

#2421 fix(llamaindex): workflow context detach exception and span names
  packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/dispatcher_wrapper.py
  packages/opentelemetry-instrumentation-llamaindex/poetry.lock
  packages/opentelemetry-instrumentation-llamaindex/pyproject.toml
  packages/sample-app/poetry.lock
  packages/sample-app/pyproject.toml
  packages/sample-app/sample_app/llama_index_workflow_app.py
Labels: bug, python, size:L, lgtm

#2442 feat(sdk): combine async/sync decorators & annotations
  packages/sample-app/sample_app/async_anthropic_example.py
  packages/sample-app/sample_app/async_anthropic_joke_streaming.py
  packages/sample-app/sample_app/async_methods_decorated_app.py
  packages/sample-app/sample_app/gemini.py
  packages/sample-app/sample_app/openai_functions.py
  packages/sample-app/sample_app/vertexai_streaming.py
  packages/traceloop-sdk/tests/test_workflows.py
  packages/traceloop-sdk/traceloop/sdk/decorators/__init__.py
  packages/traceloop-sdk/traceloop/sdk/decorators/base.py
Labels: python, testing, size:L, lgtm

#2450 chore(deps): jinja2 3.1.5 + aiohttp 3.11.11 (security)
  packages/opentelemetry-instrumentation-chromadb/poetry.lock
  packages/opentelemetry-instrumentation-langchain/poetry.lock
  packages/opentelemetry-instrumentation-llamaindex/poetry.lock
  packages/opentelemetry-instrumentation-mistralai/poetry.lock
  packages/opentelemetry-instrumentation-pinecone/poetry.lock
  packages/opentelemetry-instrumentation-weaviate/poetry.lock
  packages/sample-app/poetry.lock
  packages/traceloop-sdk/poetry.lock
  packages/traceloop-sdk/pyproject.toml
Labels: dependencies, size:XS, lgtm
