Repository traceloop/openllmetry, pull requests merged in 2024-11, with the labels that each got.

#2237 fix(llamaindex): streaming LLMs caused detached spans
  packages/opentelemetry-instrumentation-llamaindex/opentelemetry/instrumentation/llamaindex/dispatcher_wrapper.py
  packages/opentelemetry-instrumentation-llamaindex/poetry.lock
  packages/opentelemetry-instrumentation-llamaindex/pyproject.toml
  packages/opentelemetry-instrumentation-llamaindex/tests/conftest.py
  packages/opentelemetry-instrumentation-llamaindex/tests/test_agents.py
  packages/opentelemetry-instrumentation-llamaindex/tests/test_chroma_vector_store.py
  packages/opentelemetry-instrumentation-llamaindex/tests/test_query_pipeline.py
Labels: bug, python, size:L, lgtm

#2238 fix(anthropic): instrument anthropics system message as gen_ai.prompt.0
  packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py
  packages/opentelemetry-instrumentation-anthropic/tests/test_completion.py
Labels: python, testing, size:M, lgtm

#2252 fix(sdk): don't serialize large jsons as inputs/outputs
  packages/traceloop-sdk/traceloop/sdk/decorators/base.py
Labels: size:M, lgtm

#2253 fix(vertex): async / streaming was missing output fields
  packages/opentelemetry-instrumentation-vertexai/opentelemetry/instrumentation/vertexai/__init__.py
  packages/sample-app/sample_app/vertexai_streaming.py
Labels: python, size:L, lgtm

#2270 docs(destinations): add link to Highlight destination in README
  README.md
Labels: documentation, size:S, lgtm

#2274 fix: general bump of otel dependencies
  packages/opentelemetry-instrumentation-alephalpha/poetry.lock
  packages/opentelemetry-instrumentation-alephalpha/pyproject.toml
  packages/opentelemetry-instrumentation-anthropic/poetry.lock
  packages/opentelemetry-instrumentation-anthropic/pyproject.toml
  packages/opentelemetry-instrumentation-bedrock/poetry.lock
  packages/opentelemetry-instrumentation-bedrock/pyproject.toml
  packages/opentelemetry-instrumentation-chromadb/poetry.lock
  packages/opentelemetry-instrumentation-chromadb/pyproject.toml
  packages/opentelemetry-instrumentation-cohere/poetry.lock
  packages/opentelemetry-instrumentation-cohere/pyproject.toml
  packages/opentelemetry-instrumentation-google-generativeai/poetry.lock
  packages/opentelemetry-instrumentation-google-generativeai/pyproject.toml
  packages/opentelemetry-instrumentation-groq/poetry.lock
  packages/opentelemetry-instrumentation-groq/pyproject.toml
  packages/opentelemetry-instrumentation-haystack/poetry.lock
  packages/opentelemetry-instrumentation-haystack/pyproject.toml
  packages/opentelemetry-instrumentation-lancedb/poetry.lock
  packages/opentelemetry-instrumentation-lancedb/pyproject.toml
  packages/opentelemetry-instrumentation-langchain/poetry.lock
  packages/opentelemetry-instrumentation-langchain/pyproject.toml
  packages/opentelemetry-instrumentation-llamaindex/poetry.lock
  packages/opentelemetry-instrumentation-llamaindex/pyproject.toml
  packages/opentelemetry-instrumentation-marqo/poetry.lock
  packages/opentelemetry-instrumentation-marqo/pyproject.toml
  packages/opentelemetry-instrumentation-milvus/poetry.lock
  packages/opentelemetry-instrumentation-milvus/pyproject.toml
  packages/opentelemetry-instrumentation-mistralai/poetry.lock
  packages/opentelemetry-instrumentation-mistralai/pyproject.toml
  packages/opentelemetry-instrumentation-ollama/poetry.lock
  packages/opentelemetry-instrumentation-ollama/pyproject.toml
  packages/opentelemetry-instrumentation-openai/poetry.lock
  packages/opentelemetry-instrumentation-openai/pyproject.toml
  packages/opentelemetry-instrumentation-pinecone/poetry.lock
  packages/opentelemetry-instrumentation-pinecone/pyproject.toml
  packages/opentelemetry-instrumentation-qdrant/poetry.lock
  packages/opentelemetry-instrumentation-qdrant/pyproject.toml
  packages/opentelemetry-instrumentation-replicate/poetry.lock
  packages/opentelemetry-instrumentation-replicate/pyproject.toml
  packages/opentelemetry-instrumentation-sagemaker/poetry.lock
  packages/opentelemetry-instrumentation-sagemaker/pyproject.toml
  packages/opentelemetry-instrumentation-together/poetry.lock
  packages/opentelemetry-instrumentation-together/pyproject.toml
  packages/opentelemetry-instrumentation-transformers/poetry.lock
  packages/opentelemetry-instrumentation-transformers/pyproject.toml
  packages/opentelemetry-instrumentation-vertexai/poetry.lock
  packages/opentelemetry-instrumentation-vertexai/pyproject.toml
  packages/opentelemetry-instrumentation-watsonx/poetry.lock
  packages/opentelemetry-instrumentation-watsonx/pyproject.toml
  packages/opentelemetry-instrumentation-weaviate/poetry.lock
  packages/opentelemetry-instrumentation-weaviate/pyproject.toml
  packages/sample-app/poetry.lock
  packages/traceloop-sdk/poetry.lock
  packages/traceloop-sdk/pyproject.toml
  packages/traceloop-sdk/traceloop/sdk/utils/package_check.py
Labels: dependencies, size:L, lgtm

#2285 fix(sdk): remove print
  packages/traceloop-sdk/traceloop/sdk/utils/package_check.py
Labels: size:XS

#2288 fix(sdk): gemini instrumentation was never installed due to package name error
  packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Labels: bug, size:XS, lgtm

#2289 fix(cohere): rerank exception on saving response when return_documents=True
  packages/opentelemetry-instrumentation-cohere/opentelemetry/instrumentation/cohere/__init__.py
Labels: python, size:XS, lgtm

#2302 docs(readme): add Braintrust to integrations list
  README.md
Labels: documentation, size:XS, lgtm

#2305 docs(integrations): dash0 integration in readme
  README.md
Labels: documentation, size:XS, lgtm

#2321 fix(openai): Add trace context to client requests
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/__init__.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/__init__.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/completion_wrappers.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/config.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/embeddings_wrappers.py
  packages/opentelemetry-instrumentation-openai/tests/conftest.py
  packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_chat/test_chat_async_context_propagation.yaml
  packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_chat/test_chat_context_propagation.yaml
  packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_completions/test_async_completion_context_propagation.yaml
  packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_completions/test_completion_context_propagation.yaml
  packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_embeddings/test_async_embeddings_context_propagation.yaml
  packages/opentelemetry-instrumentation-openai/tests/traces/cassettes/test_embeddings/test_embeddings_context_propagation.yaml
  packages/opentelemetry-instrumentation-openai/tests/traces/test_chat.py
  packages/opentelemetry-instrumentation-openai/tests/traces/test_completions.py
  packages/opentelemetry-instrumentation-openai/tests/traces/test_embeddings.py
  packages/opentelemetry-instrumentation-openai/tests/traces/utils.py
Labels: python, testing, size:XL, lgtm

#2323 fix(openai): Add token count and system to assistants
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/v1/assistant_wrappers.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/v1/event_handler_wrapper.py
  packages/opentelemetry-instrumentation-openai/tests/traces/test_assistant.py
Labels: python, testing, size:M, lgtm
