Repository traceloop/openllmetry, pull requests merged in 2024-08, with the labels that each got.

#1901 fix(langchain): add missing kind property
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
Labels: python, size:XS, lgtm

#1902 Correct the package names for watsonx
  packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Labels: python, size:XS, lgtm

#1837 feat(instrumentation): Import redis from OpenTelemetry, add redis sample rag application
  packages/sample-app/data/sherlock/firstchapter.txt
  packages/sample-app/sample_app/redis_rag_app.py
  packages/traceloop-sdk/traceloop/sdk/instruments.py
  packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Labels: size:L

#1905 chore(deps): upgrade opentelemetry libraries to 1.27.0/0.48b0
  packages/opentelemetry-instrumentation-alephalpha/poetry.lock
  packages/opentelemetry-instrumentation-alephalpha/pyproject.toml
  packages/opentelemetry-instrumentation-anthropic/poetry.lock
  packages/opentelemetry-instrumentation-anthropic/pyproject.toml
  packages/opentelemetry-instrumentation-bedrock/poetry.lock
  packages/opentelemetry-instrumentation-bedrock/pyproject.toml
  packages/opentelemetry-instrumentation-chromadb/poetry.lock
  packages/opentelemetry-instrumentation-chromadb/pyproject.toml
  packages/opentelemetry-instrumentation-cohere/poetry.lock
  packages/opentelemetry-instrumentation-cohere/pyproject.toml
  packages/opentelemetry-instrumentation-google-generativeai/poetry.lock
  packages/opentelemetry-instrumentation-google-generativeai/pyproject.toml
  packages/opentelemetry-instrumentation-haystack/poetry.lock
  packages/opentelemetry-instrumentation-haystack/pyproject.toml
  packages/opentelemetry-instrumentation-lancedb/poetry.lock
  packages/opentelemetry-instrumentation-lancedb/pyproject.toml
  packages/opentelemetry-instrumentation-langchain/poetry.lock
  packages/opentelemetry-instrumentation-langchain/pyproject.toml
  packages/opentelemetry-instrumentation-llamaindex/poetry.lock
  packages/opentelemetry-instrumentation-llamaindex/pyproject.toml
  packages/opentelemetry-instrumentation-marqo/poetry.lock
  packages/opentelemetry-instrumentation-marqo/pyproject.toml
  packages/opentelemetry-instrumentation-milvus/poetry.lock
  packages/opentelemetry-instrumentation-milvus/pyproject.toml
  packages/opentelemetry-instrumentation-mistralai/poetry.lock
  packages/opentelemetry-instrumentation-mistralai/pyproject.toml
  packages/opentelemetry-instrumentation-ollama/poetry.lock
  packages/opentelemetry-instrumentation-ollama/pyproject.toml
  packages/opentelemetry-instrumentation-openai/poetry.lock
  packages/opentelemetry-instrumentation-openai/pyproject.toml
  packages/opentelemetry-instrumentation-pinecone/poetry.lock
  packages/opentelemetry-instrumentation-pinecone/pyproject.toml
  packages/opentelemetry-instrumentation-qdrant/poetry.lock
  packages/opentelemetry-instrumentation-qdrant/pyproject.toml
  packages/opentelemetry-instrumentation-replicate/poetry.lock
  packages/opentelemetry-instrumentation-replicate/pyproject.toml
  packages/opentelemetry-instrumentation-together/poetry.lock
  packages/opentelemetry-instrumentation-together/pyproject.toml
  packages/opentelemetry-instrumentation-transformers/poetry.lock
  packages/opentelemetry-instrumentation-transformers/pyproject.toml
  packages/opentelemetry-instrumentation-vertexai/poetry.lock
  packages/opentelemetry-instrumentation-vertexai/pyproject.toml
  packages/opentelemetry-instrumentation-watsonx/poetry.lock
  packages/opentelemetry-instrumentation-watsonx/pyproject.toml
  packages/opentelemetry-instrumentation-weaviate/poetry.lock
  packages/opentelemetry-instrumentation-weaviate/pyproject.toml
  packages/sample-app/poetry.lock
  packages/traceloop-sdk/poetry.lock
  packages/traceloop-sdk/pyproject.toml
Labels: dependencies, size:L, lgtm

#1914 fix(bedrock): llama3 completion wasnt logged
  packages/opentelemetry-instrumentation-bedrock/opentelemetry/instrumentation/bedrock/__init__.py
  packages/opentelemetry-instrumentation-bedrock/tests/cassettes/test_meta/test_meta_llama2_completion_string_content.yaml
  packages/opentelemetry-instrumentation-bedrock/tests/cassettes/test_meta/test_meta_llama3_completion.yaml
  packages/opentelemetry-instrumentation-bedrock/tests/test_meta.py
Labels: bug, size:L, lgtm

#1922 fix(langchain): allow external and langchain metadata
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
  packages/traceloop-sdk/tests/cassettes/test_association_properties/test_langchain_and_external_association_properties.yaml
  packages/traceloop-sdk/tests/test_association_properties.py
Labels: python, size:L
