Repository traceloop/openllmetry, pull requests merged in 2025-02, with the labels that each got.

#2576 feat(crewai): Implemented histogram for crewai instrumentation
  packages/opentelemetry-instrumentation-crewai/opentelemetry/instrumentation/crewai/instrumentation.py
Labels: python, size:L, lgtm

#2577 Check package version at import for better performance. Fix #2547
  packages/opentelemetry-instrumentation-groq/opentelemetry/instrumentation/groq/utils.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/__init__.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/utils.py
Labels: python, size:S, lgtm

#2600 fix(sdk): watsonx package name was wrong preventing instrumentation
  packages/sample-app/poetry.lock
  packages/sample-app/pyproject.toml
  packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Labels: bug, size:S

#2601 fix(openai): don't eagerly import types from openai as they may not be available
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/__init__.py
Labels: bug, python, size:S

#2603 fix: dependency issue for python 3.13
  packages/opentelemetry-instrumentation-crewai/poetry.lock
  packages/opentelemetry-instrumentation-crewai/pyproject.toml
  packages/opentelemetry-instrumentation-langchain/poetry.lock
  packages/opentelemetry-instrumentation-llamaindex/poetry.lock
  packages/opentelemetry-instrumentation-pinecone/poetry.lock
  packages/opentelemetry-instrumentation-weaviate/poetry.lock
  packages/sample-app/poetry.lock
  packages/traceloop-sdk/poetry.lock
  packages/traceloop-sdk/pyproject.toml
Labels: dependencies, size:XS

#2604 fix(openai): report exceptions on spans
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/completion_wrappers.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/embeddings_wrappers.py
Labels: bug, python, size:S

#2606 fix(openai): support context propagation for OpenAI v0 and v1
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/__init__.py
Labels: python, size:S, lgtm

#2607 fix(sdk): improve package name detection for metadata
  packages/traceloop-sdk/traceloop/sdk/utils/package_check.py
Labels: size:S, lgtm

#2608 fix(langchain): sanitize metadata
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
Labels: bug, python, size:M

#2618 fix(sdk): improve package name detection with type hints and null safety
  packages/traceloop-sdk/traceloop/sdk/utils/package_check.py
Labels: size:S, lgtm

#2628 fix(sdk) - Fix async decorator input & output json encoder
  packages/traceloop-sdk/traceloop/sdk/decorators/base.py
Labels: bug, size:XS, lgtm

#2633 fix(instrumentation): watsonx initialize parameters
  packages/opentelemetry-instrumentation-watsonx/opentelemetry/instrumentation/watsonx/__init__.py
Labels: python, size:XS, lgtm

#2635 fix(sdk): async generator wrapping
  packages/traceloop-sdk/tests/test_workflows.py
  packages/traceloop-sdk/traceloop/sdk/decorators/base.py
Labels: python, size:M, lgtm

#2663 fix(groq): streaming support
  packages/opentelemetry-instrumentation-groq/opentelemetry/instrumentation/groq/__init__.py
  packages/opentelemetry-instrumentation-groq/poetry.lock
  packages/opentelemetry-instrumentation-groq/pyproject.toml
  packages/opentelemetry-instrumentation-groq/tests/traces/cassettes/test_chat_tracing/test_chat_streaming.yaml
  packages/opentelemetry-instrumentation-groq/tests/traces/conftest.py
  packages/opentelemetry-instrumentation-groq/tests/traces/test_chat_tracing.py
Labels: python, testing, size:XL

#2664 fix(langchain): handle errors
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
Labels: bug, size:M

#2665 fix(langchain): warning with mixed metadata value types
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
Labels: bug, size:XS

#2685 fix(groq): Updated the instrumentation to collect the token histogram
  packages/opentelemetry-instrumentation-groq/opentelemetry/instrumentation/groq/__init__.py
Labels: python, size:S, lgtm

#2689 fix(vertexai): support generative model chat session tracing
  packages/opentelemetry-instrumentation-vertexai/opentelemetry/instrumentation/vertexai/__init__.py
  packages/sample-app/poetry.lock
  packages/sample-app/pyproject.toml
Labels: python, size:S
