Repository traceloop/openllmetry, pull requests merged in 2025-03, with the labels that each got.

#2727 fix(milvus):Added new Semantic Conventions
  packages/opentelemetry-semantic-conventions-ai/opentelemetry/semconv_ai/__init__.py
  packages/opentelemetry-semantic-conventions-ai/opentelemetry/semconv_ai/version.py
  packages/opentelemetry-semantic-conventions-ai/pyproject.toml
Labels: python, size:S

#2687 fix(milvus):Updated the instrumentation to collect get() and create_collection() span attributes
  packages/opentelemetry-instrumentation-milvus/opentelemetry/instrumentation/milvus/__init__.py
  packages/opentelemetry-instrumentation-milvus/opentelemetry/instrumentation/milvus/wrapper.py
  packages/opentelemetry-instrumentation-milvus/poetry.lock
  packages/opentelemetry-instrumentation-milvus/pyproject.toml
  packages/opentelemetry-instrumentation-milvus/tests/test_query.py
Labels: python, size:L

#2743 fix(sdk): When tracing task with no `name` provided , use qualified name instaed of name
  packages/traceloop-sdk/traceloop/sdk/decorators/base.py
Labels: enhancement, size:XS

#2754 fix(sdk): client shouldn't be initialized if destination is not traceloop
  packages/traceloop-sdk/traceloop/sdk/__init__.py
Labels: bug, size:M

#2741 fix(ollama): Implemented meter in the instrumentation
  packages/opentelemetry-instrumentation-ollama/opentelemetry/instrumentation/ollama/__init__.py
  packages/opentelemetry-instrumentation-ollama/poetry.lock
  packages/opentelemetry-instrumentation-ollama/tests/test_chat.py
  packages/traceloop-sdk/poetry.lock
Labels: new instrumentation, size:L
