Repository traceloop/openllmetry, pull requests merged in 2025-01, with the labels that each got.

#2453 docs: document telemetry collection in README
  README.md
  packages/traceloop-sdk/traceloop/sdk/__init__.py
Labels: documentation, size:S

#2454 fix(sdk): option to disable SDK
  packages/traceloop-sdk/traceloop/sdk/__init__.py
  packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py
Labels: bug, size:S

#2452 feat(sdk): client, annotations
  packages/sample-app/sample_app/methods_decorated_app.py
  packages/traceloop-sdk/tests/test_client.py
  packages/traceloop-sdk/tests/test_user_feedback.py
  packages/traceloop-sdk/traceloop/sdk/__init__.py
  packages/traceloop-sdk/traceloop/sdk/annotation/__init__.py
  packages/traceloop-sdk/traceloop/sdk/annotation/base_annotation.py
  packages/traceloop-sdk/traceloop/sdk/annotation/user_feedback.py
  packages/traceloop-sdk/traceloop/sdk/client/__init__.py
  packages/traceloop-sdk/traceloop/sdk/client/client.py
  packages/traceloop-sdk/traceloop/sdk/client/http.py
  packages/traceloop-sdk/traceloop/sdk/fetcher.py
Labels: python, testing, size:L

#2511 fix(gemini): set prompt attributes for role and content
  packages/opentelemetry-instrumentation-google-generativeai/opentelemetry/instrumentation/google_generativeai/__init__.py
  packages/opentelemetry-instrumentation-google-generativeai/poetry.lock
  packages/opentelemetry-instrumentation-google-generativeai/pyproject.toml
  packages/opentelemetry-instrumentation-google-generativeai/tests/conftest.py
  packages/opentelemetry-instrumentation-google-generativeai/tests/test_generate_content.py
  packages/opentelemetry-instrumentation-google-generativeai/tests/test_placeholder.py
Labels: python, testing, size:M

#2536 fix(sdk): remove use of `__all__`
  packages/traceloop-sdk/traceloop/sdk/__init__.py
  packages/traceloop-sdk/traceloop/sdk/annotation/__init__.py
  packages/traceloop-sdk/traceloop/sdk/client/__init__.py
Labels: python, size:XS, lgtm

#2539 fix(langchain): address warning for NoneType attibute; update some test deps
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
  packages/opentelemetry-instrumentation-langchain/poetry.lock
  packages/opentelemetry-instrumentation-langchain/pyproject.toml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_structured_output/test_structured_output.yaml
  packages/opentelemetry-instrumentation-langchain/tests/cassettes/test_tool_calls/test_tool_calls.yaml
  packages/opentelemetry-instrumentation-langchain/tests/test_lcel.py
  packages/opentelemetry-instrumentation-langchain/tests/test_llms.py
  packages/opentelemetry-instrumentation-langchain/tests/test_structured_output.py
  packages/opentelemetry-instrumentation-langchain/tests/test_tool_calls.py
Labels: python, testing, size:L, lgtm

#2546 fix(groq): add response id attribute
  packages/opentelemetry-instrumentation-groq/opentelemetry/instrumentation/groq/__init__.py
  packages/opentelemetry-instrumentation-groq/tests/traces/test_chat_tracing.py
Labels: python, testing, size:XS, lgtm

#2543 fix(anthropic): add response id attribute
  packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/__init__.py
  packages/opentelemetry-instrumentation-anthropic/opentelemetry/instrumentation/anthropic/streaming.py
  packages/opentelemetry-instrumentation-anthropic/tests/test_completion.py
Labels: python, testing, size:S, lgtm

#2544 fix(bedrock): add response id attribute
  packages/opentelemetry-instrumentation-bedrock/opentelemetry/instrumentation/bedrock/__init__.py
  packages/opentelemetry-instrumentation-bedrock/tests/traces/test_ai21.py
  packages/opentelemetry-instrumentation-bedrock/tests/traces/test_anthropic.py
  packages/opentelemetry-instrumentation-bedrock/tests/traces/test_cohere.py
  packages/opentelemetry-instrumentation-bedrock/tests/traces/test_meta.py
  packages/opentelemetry-instrumentation-bedrock/tests/traces/test_titan.py
Labels: python, testing, size:S, lgtm

#2545 fix(cohere): add response id attribute
  packages/opentelemetry-instrumentation-cohere/opentelemetry/instrumentation/cohere/__init__.py
  packages/opentelemetry-instrumentation-cohere/tests/test_chat.py
  packages/opentelemetry-instrumentation-cohere/tests/test_completion.py
  packages/opentelemetry-instrumentation-cohere/tests/test_rerank.py
Labels: python, testing, size:XS, lgtm

#2559 fix: add crewai to support frameworks in readme
  README.md
Labels: documentation, size:XS

#2570 fix(crewai): instrumentation package version
  packages/opentelemetry-instrumentation-crewai/pyproject.toml
Labels: size:XS

#2548 fix(langchain): add response id (anthropic only)
  packages/opentelemetry-instrumentation-langchain/opentelemetry/instrumentation/langchain/callback_handler.py
  packages/opentelemetry-instrumentation-langchain/tests/test_llms.py
Labels: python, testing, size:XS, lgtm

#2552 chore(github): update issue template to reflect all instrumentations
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: size:S, lgtm

#2551 fix(together): add response id attribute
  packages/opentelemetry-instrumentation-together/opentelemetry/instrumentation/together/__init__.py
  packages/opentelemetry-instrumentation-together/tests/test_chat.py
  packages/opentelemetry-instrumentation-together/tests/test_completion.py
Labels: python, testing, size:XS, lgtm

#2550 fix(openai): add response id attribute
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/__init__.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/chat_wrappers.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/shared/completion_wrappers.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/v1/assistant_wrappers.py
  packages/opentelemetry-instrumentation-openai/opentelemetry/instrumentation/openai/v1/event_handler_wrapper.py
  packages/opentelemetry-instrumentation-openai/tests/traces/test_assistant.py
  packages/opentelemetry-instrumentation-openai/tests/traces/test_azure.py
  packages/opentelemetry-instrumentation-openai/tests/traces/test_chat.py
  packages/opentelemetry-instrumentation-openai/tests/traces/test_completions.py
  packages/opentelemetry-instrumentation-openai/tests/traces/test_functions.py
  packages/opentelemetry-instrumentation-openai/tests/traces/test_structured.py
  packages/opentelemetry-instrumentation-openai/tests/traces/test_vision.py
Labels: bug, size:M, lgtm

#2549 fix(mistral): add response id attribute
  packages/opentelemetry-instrumentation-mistralai/opentelemetry/instrumentation/mistralai/__init__.py
  packages/opentelemetry-instrumentation-mistralai/tests/cassettes/test_embeddings/test_mistral_embeddings.yaml
  packages/opentelemetry-instrumentation-mistralai/tests/test_chat.py
  packages/opentelemetry-instrumentation-mistralai/tests/test_embeddings.py
Labels: python, testing, size:M, lgtm
